version: '3'

services:
  rails: &rails
    build:
      context: .
      dockerfile: ./compose/development/rails/Dockerfile
    image: kidsresas_development_rails
    depends_on:
      - mysql
      - redis
    volumes:
      - kidsresas_development_node_modules:/app/node_modules
      - kidsresas_development_rails_sprockets_cache:/rails_sprockets_cache
      - .:/app
    tty: true
    ports:
      - "3000:3000"
    env_file:
      - ./.envs/.development/.rails
      - ./.envs/.development/.mysql
      - ./.envs/.development/.redis
    command: /start

  mysql:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - kidsresas_development_mysql_data:/var/lib/mysql
    env_file: 
      - ./.envs/.development/.mysql
  
  redis:
    image: redis:6.0.4-alpine

volumes:
    kidsresas_development_mysql_data:
    kidsresas_development_node_modules:
    kidsresas_development_rails_sprockets_cache: