version: '3'

services:
  rails: &rails
    build:
      context: .
      dockerfile: ./compose/production/rails/Dockerfile
    image: kidsresas_production_rails
    depends_on:
      - mysql
      - redis
    volumes:
      - kidsresas_production_rails_asset_data:/app/public/assets
      - kidsresas_production_rails_upload_data:/app/public/uploads
      - kidsresas_production_node_modules:/app/node_modules
    env_file:
      - ./.envs/.production/.rails
      - ./.envs/.production/.mysql
      - ./.envs/.production/.redis
    command: /start

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: kidsresas_production_nginx
    depends_on:
      - rails
    volumes:
      - kidsresas_production_nginx_data:/etc/nginx/conf.d
      - kidsresas_production_rails_asset_data:/assets
      - kidsresas_production_rails_upload_data:/uploads
    ports:
      - "0.0.0.0:80:3000"

  mysql:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password    
    volumes:
      - kidsresas_production_mysql_data:/var/lib/mysql
    env_file: 
      - ./.envs/.production/.mysql
  
  redis:
    image: redis:6.0.4-alpine
  
volumes:
  kidsresas_production_mysql_data:
  kidsresas_production_node_modules:
  kidsresas_production_nginx_data:
  kidsresas_production_rails_asset_data:
  kidsresas_production_rails_upload_data: