default: &default
  adapter: redis  
  host: <%= ENV["REDIS_HOST"] %>
  port: <%= ENV["REDIS_PORT"] %>

development:
  <<: *default
  channel_prefix: <%= ENV["REDIS_CHANNEL_PREFIX"] %>

test:
  adapter: test

production:
  <<: *default
  channel_prefix: <%= ENV["REDIS_CHANNEL_PREFIX"] %>
