default: &default
  adapter: redis
  host: <%= ENV["REDIS_HOST"] %>
  port: <%= ENV["REDIS_PORT"] %>
  
development:
  <<: *default
  channel_prefix: kidsresas_development

test:
  <<: *default
  channel_prefix: kidsresas_test

production:
  <<: *default
  channel_prefix: kidsresas_production
